// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/posts": {
            "post": {
                "description": "投稿を新規作成する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "CreatePost",
                "parameters": [
                    {
                        "description": "投稿作成リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PostCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PostCreateResponse"
                        }
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "description": "ユーザーを新規作成する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "CreateUser",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.UserSignupResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.PostCreateRequest": {
            "type": "object",
            "required": [
                "content",
                "nickname",
                "novel"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "novel": {
                    "type": "string"
                }
            }
        },
        "response.PostCreateResponse": {
            "type": "object",
            "required": [
                "content",
                "createdAt",
                "id",
                "nickname",
                "novel",
                "updatedAt",
                "userId"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "novel": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "response.UserSignupResponse": {
            "type": "object",
            "required": [
                "accessToken",
                "createdAt",
                "id",
                "name",
                "password",
                "refreshToken",
                "updatedAt"
            ],
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "http://localhost:8089",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "yumemi backend API",
	Description:      "YumemibanのAPIサーバー",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
